name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace API Key
        run: |
          sed -i "s/YOUR_API_KEY_PLACEHOLDER/${{ secrets.WEATHER_API_KEY }}/g" app.js
          echo "API Key replaced successfully"
          grep -n "apiKey" app.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
